#!/bin/bash

set -e

die() {
	echo "error: $1" >&2
	exit 1
}

typst_common_dir=$(dirname "$0")
cd $typst_common_dir

[ -d ".git" ] || die "typst-common/ is not a git repository"

git fetch origin
git merge --squash --quiet origin/main || die "merge conflicts detected"

if git diff --cached --quiet; then
	echo "already up to date"
else
	git commit -m "Update typst-common/lib"
fi
